sts:
  # hostPort is required for the secure setup because it does not work without host header checking
  # and we need a deterministic port to access
  hostPort: 443

loadBalancer:
  enabled:
    false

zookeeper:
  # Number of ZooKeeper replicas
  servers: 1

  ## Configure Zookeeper resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      memory: "256Mi"
    requests:
      memory: "128Mi"

  antiAffinity: "soft"

  ## The JVM heap size to allocate to Zookeeper
  heap: "128m"