apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-creator
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-10"
  labels:
    chart: {{ template "apache-nifi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-creator
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-9"
  labels:
    chart: {{ template "apache-nifi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-creator
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-8"
  labels:
    chart: {{ template "apache-nifi.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: secret-creator
roleRef:
  kind: Role
  name: secret-creator
  apiGroup: rbac.authorization.k8s.io